
architecture: replicaset
replicaCount: 3
## @param useStatefulSet Set to true to use a StatefulSet instead of a Deployment (only when `architecture=standalone`)
##
arbiter:
  enabled: false

useStatefulSet: false
storageclass: ""
tolerations:
  - key: "statefulset/special-taint"
    operator: "Equal"
        #value: "true"  # Use the taint's value, if the taint was key-value paired.
    effect: "NoSchedule"      
persistence:
  enabled: false

affinity:
  podAntiAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - mongodb
        topologyKey: "kubernetes.io/hostname"
  nodeAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:
     nodeSelectorTerms:
     - matchExpressions:
       - key: statefulset/special-taint
         operator: In
         values:
         - stateful