apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
 name: gitlab-auto-nodepool
spec:
  template:
    metadata:
      labels:
        workload-type: gitlab-runners-auto
    spec:
      taints:
        - effect: NoSchedule
          key: dedicated
          value: gitlab-runner-auto
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["t3"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["2xlarge"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        name: default
  limits:
    cpu: "32"
    memory: "64Gi"
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h    
    