---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-karpenter-test2
  region: eu-west-1
  version: "1.23" 

vpc:
  subnets:
    private:
      eu-west-1a: { id: subnet-0bd9dbc8d1d824c16 }
      eu-west-1b: { id: subnet-0aa169c9fab25f42d }

managedNodeGroups:
  - name: test-workers-2
    labels: { role: workers }
    instanceType: t3a.xlarge
    desiredCapacity: 1
    volumeSize: 150
    privateNetworking: true
    subnets:
      - subnet-0bd9dbc8d1d824c16
    iam:
      withAddonPolicies:        
        ebs: true
        fsx: true
        efs: true
  
