apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: karpenter-nodepool
spec:
  template:
    metadata:
      labels:
        statefulset/special-taint: stateful
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          #values: ["spot", "on-demand"]
          values: ["spot"]
      #  - key: karpenter.k8s.aws/instance-category
      #    operator: In
      #    values: ["c", "m", "r"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3a.2xlarge", "t3a.xlarge", "c5a.4xlarge", "c5a.2xlarge", "c5a.xlarge"]      
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        name: default
      taints:
        - key: statefulset/special-taint
          effect: NoSchedule        
 # limits:
 #   cpu: 1150
  disruption:
    #consolidationPolicy: WhenEmpty
    #consolidateAfter: 1s
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2 # Amazon Linux 2
  role: "TSGSKarpenterInstanceNodeRole" # replace with your cluster name
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "tsgs-saas-aws" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "tsgs-saas-aws" # replace with your cluster name