cp-kafka-connect:
  namespace: rafael-tsgs-test-flight
  label_selector: "app=cp-kafka-connect"
  resource_type: "Deployment"
mongodb:
  namespace: rafael-tsgs-test-flight
  label_selector: "app.kubernetes.io/name=mongodb"
  resource_type: "StatefulSet"
  connection_string: "mongodb://tsgsuser:tsgspassword@k8s-rafaelts-mongo5rs-ffe2b033dd-90b7ef1b36237c61.elb.eu-west-1.amazonaws.com:27017/tsgsdb?authSource=admin&directConnection=true"
  database_name: "tsgsdb"  
  username: "tsgsuser"  
  password: "tsgspassword"    
jaeger-query:
  namespace: rafael-tsgs-test-flight
  label_selector: "app.kubernetes.io/component=query"
  resource_type: "Deployment"
jaeger-collector:
  namespace: rafael-tsgs-test-flight
  label_selector: "app.kubernetes.io/component=collector"
  resource_type: "Deployment"
