---
# Source: checklist-chart-test/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-checklist-chart-test
  labels:
    helm.sh/chart: checklist-chart-test-0.1.0
    app.kubernetes.io/name: checklist-chart-test
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: checklist-chart-test/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: checklist-config
data:
  config.json: |-
        {
          "apps": {
            "mongodb": {
              "type": "mongodb",
              "endpoint": "k8s-rafaelts-mongo5rs-0a7a2695e2-fb36d2b62b7dae0c.elb.eu-west-1.amazonaws.com:27017",
              "database_name": "tsgsdb",
              "username": "tsgsuser",
              "password": "tsgspassword"
            }
          },
          "configMapCheck": {
            "name": "trusted-ca",
            "namespace": "rafael-tsgs-cicd-flight"
          },
          "secretsChecks": [
            {
              "name": "tsgs-registry",
              "namespace": "rafael-tsgs-cicd-flight"
            },
            {
              "name": "tsinf-reg",
              "namespace": "rafael-tsgs-cicd-flight"
            }
          ],
        
          "applicationChecks": [
            {
              "name": "zalenium",
              "namespace": "rafael-tsgs-cicd-flight"
            },
            {
              "name": "locust",
              "namespace": "rafael-tsgs-cicd-flight"
            },
            {
              "name": "app-of-apps",
              "namespace": "rafael-tsgs-cicd-flight"
            }    
          ],
          "clusterLogForwarderDetails": {
            "name": "instance",
            "namespace": "openshift-logging",
            "targetNamespace": "rafael-tsgs-cicd-flight"
          },
          "jaegerCheck": {
            "namespace": "rafael-tsgs-cicd-flight",
            "expectedJaegerEndpoint": "k8s-rafaelts-jaegerra-db787948a8-ed4d8fd624330e8c.elb.eu-west-1.amazonaws.com:14250"
          },  
          "deploymentCheck": {
            "namespace": "rafael-tsgs-cicd-flight",
            "partialName": "sealed-secrets"
          },
          "prometheusCheck": {
            "endpoint": "http://prometheus.tsgs-saas-aws.wwest.local/",
            "jobName": "otel-collector-cicd-flight"
          },
          "elasticsearchCheck": {
            "endpoint": "http://elasticsearch.tsgs-saas-aws.wwest.local",
            "partialIndexName": "rafael-tsgs-cicd-flight"
          }
        }
---
# Source: checklist-chart-test/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-checklist-chart-test
  labels:
    helm.sh/chart: checklist-chart-test-0.1.0
    app.kubernetes.io/name: checklist-chart-test
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: checklist-chart-test
    app.kubernetes.io/instance: release-name
---
# Source: checklist-chart-test/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-checklist-chart-test
  labels:
    helm.sh/chart: checklist-chart-test-0.1.0
    app.kubernetes.io/name: checklist-chart-test
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: checklist-chart-test
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        helm.sh/chart: checklist-chart-test-0.1.0
        app.kubernetes.io/name: checklist-chart-test
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      imagePullSecrets:
        - name: tsgs-registry
      serviceAccountName: release-name-checklist-chart-test
      containers:
        - name: checklist-chart-test-apache
          image: "artifactory.rafael.co.il:6001/infra/apache:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: apache-data
              mountPath: /var/www/html  # Apache document root              
        - name: checklist-chart-test-app
          image: "artifactory.rafael.co.il:6001/infra/checklist:v8"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: apache-data
              mountPath: /data  # Apache document root  
            - name: configmap-volume
              mountPath: /etc/script-config                        
          resources:
            {}
      volumes:
        - emptyDir: {}
          name: apache-data
        - configMap:
            name: checklist-config
          name: configmap-volume
---
# Source: checklist-chart-test/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "release-name-checklist-chart-test-test-connection"
  labels:
    helm.sh/chart: checklist-chart-test-0.1.0
    app.kubernetes.io/name: checklist-chart-test
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['release-name-checklist-chart-test:80']
  restartPolicy: Never
